package com.greenrou.kanata.ui.theme

import androidx.compose.ui.graphics.Color

val AnimeLight_Primary = Color(0xFF5B21B6)
val AnimeLight_OnPrimary = Color(0xFFFFFFFF)
val AnimeLight_PrimaryContainer = Color(0xFFEDE9FE)
val AnimeLight_OnPrimaryContainer = Color(0xFF2E0065)
val AnimeLight_Secondary = Color(0xFFDB2777)
val AnimeLight_OnSecondary = Color(0xFFFFFFFF)
val AnimeLight_SecondaryContainer = Color(0xFFFFE4F0)
val AnimeLight_OnSecondaryContainer = Color(0xFF5C0030)
val AnimeLight_Tertiary = Color(0xFF0891B2)
val AnimeLight_OnTertiary = Color(0xFFFFFFFF)
val AnimeLight_TertiaryContainer = Color(0xFFCFF7FE)
val AnimeLight_OnTertiaryContainer = Color(0xFF003541)
val AnimeLight_Background = Color(0xFFFAF5FF)
val AnimeLight_OnBackground = Color(0xFF120E1A)
val AnimeLight_Surface = Color(0xFFFAF5FF)
val AnimeLight_OnSurface = Color(0xFF120E1A)
val AnimeLight_SurfaceVariant = Color(0xFFEDE9F6)
val AnimeLight_OnSurfaceVariant = Color(0xFF49454F)
val AnimeLight_SurfaceContainer = Color(0xFFF3EFFE)
val AnimeLight_SurfaceContainerHigh = Color(0xFFECE6F8)
val AnimeLight_SurfaceContainerHighest = Color(0xFFE4DEF2)
val AnimeLight_Outline = Color(0xFF79747E)
val AnimeLight_OutlineVariant = Color(0xFFCBC4D0)

val AnimeDark_Primary = Color(0xFFC4B5FD)
val AnimeDark_OnPrimary = Color(0xFF3B0087)
val AnimeDark_PrimaryContainer = Color(0xFF4C1D95)
val AnimeDark_OnPrimaryContainer = Color(0xFFEDE9FE)
val AnimeDark_Secondary = Color(0xFFF9A8D4)
val AnimeDark_OnSecondary = Color(0xFF700040)
val AnimeDark_SecondaryContainer = Color(0xFF9B1B5B)
val AnimeDark_OnSecondaryContainer = Color(0xFFFFE4F0)
val AnimeDark_Tertiary = Color(0xFF67E8F9)
val AnimeDark_OnTertiary = Color(0xFF003C47)
val AnimeDark_TertiaryContainer = Color(0xFF006880)
val AnimeDark_OnTertiaryContainer = Color(0xFFCFF7FE)
val AnimeDark_Background = Color(0xFF0A0910)
val AnimeDark_OnBackground = Color(0xFFEAE5F4)
val AnimeDark_Surface = Color(0xFF0A0910)
val AnimeDark_OnSurface = Color(0xFFEAE5F4)
val AnimeDark_SurfaceVariant = Color(0xFF3B3545)
val AnimeDark_OnSurfaceVariant = Color(0xFFCBC4D0)
val AnimeDark_SurfaceContainer = Color(0xFF16131F)
val AnimeDark_SurfaceContainerHigh = Color(0xFF1E1B2A)
val AnimeDark_SurfaceContainerHighest = Color(0xFF272333)
val AnimeDark_Outline = Color(0xFF948F9A)
val AnimeDark_OutlineVariant = Color(0xFF49454F)
