package com.greenrou.kanata.ui.theme

import androidx.compose.ui.graphics.Color

val AnimeLight_Primary = Color(0xFF15803D)
val AnimeLight_OnPrimary = Color(0xFFFFFFFF)
val AnimeLight_PrimaryContainer = Color(0xFFDCFCE7)
val AnimeLight_OnPrimaryContainer = Color(0xFF052E16)
val AnimeLight_Secondary = Color(0xFFDB2777)
val AnimeLight_OnSecondary = Color(0xFFFFFFFF)
val AnimeLight_SecondaryContainer = Color(0xFFFFE4F0)
val AnimeLight_OnSecondaryContainer = Color(0xFF5C0030)
val AnimeLight_Tertiary = Color(0xFF0891B2)
val AnimeLight_OnTertiary = Color(0xFFFFFFFF)
val AnimeLight_TertiaryContainer = Color(0xFFCFF7FE)
val AnimeLight_OnTertiaryContainer = Color(0xFF003541)
val AnimeLight_Background = Color(0xFFF0FDF4)
val AnimeLight_OnBackground = Color(0xFF0A1F0F)
val AnimeLight_Surface = Color(0xFFF0FDF4)
val AnimeLight_OnSurface = Color(0xFF0A1F0F)
val AnimeLight_SurfaceVariant = Color(0xFFDCFCE7)
val AnimeLight_OnSurfaceVariant = Color(0xFF374151)
val AnimeLight_SurfaceContainer = Color(0xFFECFDF5)
val AnimeLight_SurfaceContainerHigh = Color(0xFFD1FAE5)
val AnimeLight_SurfaceContainerHighest = Color(0xFFA7F3D0)
val AnimeLight_Outline = Color(0xFF6B7280)
val AnimeLight_OutlineVariant = Color(0xFFBBF7D0)

val AnimeDark_Primary = Color(0xFF4ADE80)
val AnimeDark_OnPrimary = Color(0xFF052E16)
val AnimeDark_PrimaryContainer = Color(0xFF166534)
val AnimeDark_OnPrimaryContainer = Color(0xFFDCFCE7)
val AnimeDark_Secondary = Color(0xFFF9A8D4)
val AnimeDark_OnSecondary = Color(0xFF700040)
val AnimeDark_SecondaryContainer = Color(0xFF9B1B5B)
val AnimeDark_OnSecondaryContainer = Color(0xFFFFE4F0)
val AnimeDark_Tertiary = Color(0xFF67E8F9)
val AnimeDark_OnTertiary = Color(0xFF003C47)
val AnimeDark_TertiaryContainer = Color(0xFF006880)
val AnimeDark_OnTertiaryContainer = Color(0xFFCFF7FE)
val AnimeDark_Background = Color(0xFF030D07)
val AnimeDark_OnBackground = Color(0xFFD1FAE5)
val AnimeDark_Surface = Color(0xFF030D07)
val AnimeDark_OnSurface = Color(0xFFD1FAE5)
val AnimeDark_SurfaceVariant = Color(0xFF1C3524)
val AnimeDark_OnSurfaceVariant = Color(0xFFA7F3D0)
val AnimeDark_SurfaceContainer = Color(0xFF0D1F12)
val AnimeDark_SurfaceContainerHigh = Color(0xFF162B1B)
val AnimeDark_SurfaceContainerHighest = Color(0xFF1F3A26)
val AnimeDark_Outline = Color(0xFF6B7280)
val AnimeDark_OutlineVariant = Color(0xFF2D5A3A)
